using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Sonidos : MonoBehaviour
{

    [SerializeField] private AudioClip da単oSound;
    [SerializeField] private AudioClip da単oSoundKings; //FALTA ADAPTAR
    void Update()
    {



        
    }

    void OnDestroy(){
        if (gameObject.CompareTag("Enemy"))
        {
            AudioSource.PlayClipAtPoint(da単oSound, transform.position, 1f); // Volumen a 0.3
        }
        if (gameObject.CompareTag("EnemyKing"))
        {
            AudioSource.PlayClipAtPoint(da単oSound, transform.position, 1f); // Volumen a 0.3
        }
    }
}
